# Generated by Django 4.2.2 on 2023-06-27 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_ID", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=64)),
                ("descriptions", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("Furniture", "Furniture")], max_length=64
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(choices=[("Chair", "Chair")], max_length=64),
                ),
                (
                    "material",
                    models.CharField(choices=[("Wood", "Wood")], max_length=32),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Poland", "Pl"),
                            ("Czech Republic", "Cz"),
                            ("Czechoslovakia", "Cs"),
                            ("Germany", "De"),
                            ("France", "Fr"),
                            ("Belgium", "Bg"),
                            ("Italy", "It"),
                            ("Denmark", "Dn"),
                            ("Sweden", "Se"),
                        ],
                        max_length=32,
                    ),
                ),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("length", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
                ("PKWIU", models.CharField(blank=True, max_length=32)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("purchase_cost", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                ("location", models.CharField(max_length=32)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ERP.index"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=16)),
                ("contact_person", models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_first", models.BooleanField(default=False)),
                ("images", models.ImageField(upload_to="ERP/media/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ERP.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=16)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("Free of expense", "Free"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("cost", models.IntegerField(default=0)),
                ("other_expenses", models.IntegerField(default=0)),
                ("tax", models.IntegerField(default=0)),
                ("total_cost", models.IntegerField(default=0)),
                ("purchase_date", models.DateField()),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ERP.vendors"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(max_length=16)),
                ("cost", models.IntegerField(default=0)),
                ("other_expenses", models.IntegerField(default=0)),
                ("tax", models.IntegerField(default=0)),
                ("total_cost", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ERP.product"
                    ),
                ),
                (
                    "order_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ERP.orderheader",
                    ),
                ),
            ],
        ),
    ]
