# Generated by Django 4.2.2 on 2023-06-28 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ERP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_day", models.DateField(auto_now_add=True)),
                ("descriptions", models.TextField()),
                (
                    "document_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ERP.orderheader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=64)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("Assets", "Assets"), ("Liabilities", "Liabilities")],
                        max_length=32,
                    ),
                ),
                ("basic_code", models.CharField(max_length=8)),
                ("extended_code", models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="LedgerEntries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ERP.accounts"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ERP.accountingtransactions",
                    ),
                ),
            ],
        ),
    ]
